### ISSUE TITLE
Don’t put the link to the full documentation behind a newsletter signup

### ISSUE THREAD

**Issue by herrherrmann** [dhakehurst/net.akehurst.kotlin.kt2ts#6]
Thanks for sponsoring this project, itemis (whatever IT services you seem to provide), but please do not hide the [link to the full documentation](https://www.itemis.com/en/kotlin-typescript-integration) for an open-source(!) project behind a random newsletter signup. Let’s just put the link into the readme or just put the whole documentation into the readme (where it belongs).

Thank you!

**Comment by dhakehurst** [comment]
Sorry.
The work to develop this was paid for by the company.
The agreement to make it open source requires "payment" of your email address to get the full documentation.
